### ISSUE TITLE
G90

### ISSUE THREAD

**Issue by duebelpapst** [Festivejelly/LatheGcodeVisualiser#11]
Hi,
Nice tool, but G90 doesn't seem to work.
If I use G90 instead of G91, no toolpath is displayed.

Regards,
Stefan

**Comment by Festivejelly** [comment]
As lathecode uses relative paths thats what I implemented but I will add G90 support too. Probably this weekend when I get some time.

**Comment by Festivejelly** [comment]
@duebelpapst this should be resolved now. It supports showing both absolute moves and relative moves.
